[project]
name = "deep-live-cam-cuda"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "numpy>=1.24.2,<2",
  "typing-extensions>=4.8.0",
  "opencv-python==4.10.0.84",
  "cv2_enumerate_cameras==1.1.15",
  "onnx==1.18.0",
  "insightface==0.7.3",
  "psutil==5.9.8",
  "tk==0.1.0",
  "customtkinter==5.2.2",
  "pillow==12.1.1",
  "tqdm>=4.65.0",
  "onnxruntime-gpu==1.16.3",
  "tensorflow>=2.15.0",
  "opennsfw2==0.10.2",
  "protobuf==4.25.1",
]

[tool.uv]
python-preference = "only-system"
